project_id = "hxtbsieodbtzgcvvkeqx"

[functions.zapi-proxy]
verify_jwt = true

[functions.zapi-send-message]
verify_jwt = true

[functions.zapi-send-item-added]
verify_jwt = false

[functions.zapi-send-paid-order]
verify_jwt = false

[functions.zapi-send-product-canceled]
verify_jwt = false

[functions.zapi-broadcast]
verify_jwt = true

[functions.update-zapi-client-token]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false
