project_id = "hxtbsieodbtzgcvvkeqx"

[functions.create-tenant-admin]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.melhor-envio-labels]
verify_jwt = true

[functions.melhor-envio-shipping]
verify_jwt = true

[functions.melhor-envio-test-token]
verify_jwt = true

[functions.melhor-envio-webhook]
verify_jwt = false

[functions.zapi-proxy]
verify_jwt = true

[functions.zapi-send-message]
verify_jwt = true

[functions.zapi-send-item-added]
verify_jwt = false

[functions.zapi-send-paid-order]
verify_jwt = false

[functions.zapi-send-product-canceled]
verify_jwt = false

[functions.zapi-broadcast]
verify_jwt = true

[functions.update-zapi-client-token]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send-tracking]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.sync-tracking-codes]
verify_jwt = false

[functions.bling-sync-orders]
verify_jwt = true

[functions.bling-oauth]
verify_jwt = true

[functions.bling-oauth-callback]
verify_jwt = false

[functions.mandae-shipping]
verify_jwt = true

[functions.mandae-labels]
verify_jwt = false

[functions.mandae-webhook]
verify_jwt = false
